"""empty message

Revision ID: 2156d16a6e6a
Revises: 5e7ae29248ff
Create Date: 2022-08-05 01:12:30.814848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2156d16a6e6a'
down_revision = '5e7ae29248ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('image_links', sa.String(length=500), nullable=True))
    op.drop_column('Artist', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('image_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'image_links')
    # ### end Alembic commands ###
