"""empty message

Revision ID: 690c6f93ead2
Revises: 472181ca1b04
Create Date: 2022-08-05 11:28:47.697843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690c6f93ead2'
down_revision = '472181ca1b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'id')
    # ### end Alembic commands ###
