"""empty message

Revision ID: 91122464034c
Revises: f454eb17fb31
Create Date: 2022-08-07 01:40:59.563267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91122464034c'
down_revision = 'f454eb17fb31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('booking_days', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'booking_days')
    # ### end Alembic commands ###
