"""empty message

Revision ID: b108592efae0
Revises: 690c6f93ead2
Create Date: 2022-08-05 20:03:39.813997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b108592efae0'
down_revision = '690c6f93ead2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('Artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Artist_id'], ['Artist.id'], name='shows_Artist_id_fkey'),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], name='shows_Venue_id_fkey'),
    sa.PrimaryKeyConstraint('Artist_id', 'Venue_id', name='shows_pkey')
    )
    # ### end Alembic commands ###
